---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: test
  labels:
    environment: test
    app: wordpress
spec:
  selector:
    environment: test
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: test
  labels:
    environment: test
    app: wordpress
spec:
  selector:
    environment: test
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
