---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: test
  labels:
    environment: test
    app: wordpress
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
